### ISSUE TITLE
bad plural

### ISSUE THREAD

**Issue by rhoksbergen** [nicholsk18/task-tracker#7]
https://github.com/nicholsk18/task-tracker/blob/a1d38f2fe8a75ef18c4419c76cbc920412f79230/src/models/Session.ts#L1

**Comment by rhoksbergen** [comment]
Mostly just having a play with this github issues functionality

**Comment by nicholsk18** [comment]
Fun, I am fine using issues if you want. There is also a kanban board in github if you would want to use that.
